import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  searchContainer: {
    position: 'absolute',
    top: 60,
    left: 15,
    right: 15,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    maxHeight: '75%',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  input: {
    flex: 1,
    height: 55,
    backgroundColor: '#f8f9fa',
    borderRadius: 15,
    paddingHorizontal: 20,
    fontSize: 16,
    marginRight: 10,
    borderWidth: 2,
    borderColor: '#e9ecef',
  },
  clearInputButton: {
    position: 'absolute',
    right: 80,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e9ecef',
    borderRadius: 15,
  },
  clearInputText: {
    fontSize: 16,
    color: '#666',
  },
  searchButton: {
    backgroundColor: '#4A90E2',
    width: 55,
    height: 55,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4A90E2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  searchButtonText: {
    fontSize: 24,
  },
  infoRuta: {
    marginTop: 15,
    flexDirection: 'row',
    padding: 15,
    backgroundColor: '#E8F4F8',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  infoRutaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  infoRutaIcon: {
    fontSize: 24,
  },
  infoRutaLabel: {
    fontSize: 11,
    color: '#6c757d',
    fontWeight: '500',
  },
  infoRutaValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C5F7F',
  },
  infoRutaDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#ccc',
  },
  transportMenuButton: {
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#e9ecef',
  },
  transportMenuIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  transportMenuText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  transportMenuArrow: {
    fontSize: 14,
    color: '#666',
  },
  transportOptions: {
    marginTop: 10,
    backgroundColor: '#f8f9fa',
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  transportOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  transportOptionActive: {
    backgroundColor: '#E8F4F8',
  },
  transportOptionIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  transportOptionText: {
    flex: 1,
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  transportOptionTextActive: {
    color: '#4A90E2',
    fontWeight: 'bold',
  },
  transportOptionCheck: {
    fontSize: 18,
    color: '#4A90E2',
    fontWeight: 'bold',
  },
  actionButtons: {
    flexDirection: 'row',
    marginTop: 15,
    gap: 10,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 15,
    gap: 8,
  },
  actionButtonIcon: {
    fontSize: 20,
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  trackButton: {
    backgroundColor: '#34C759',
    shadowColor: '#34C759',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  trackButtonActive: {
    backgroundColor: '#FF9500',
    shadowColor: '#FF9500',
  },
  trackButtonTextActive: {
    color: '#fff',
  },
  clearButton: {
    backgroundColor: '#FF3B30',
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  refreshButton: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5856D6',
    padding: 15,
    borderRadius: 15,
    gap: 8,
    shadowColor: '#5856D6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  refreshButtonIcon: {
    fontSize: 20,
  },
  refreshButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  suggestionsContainer: {
    marginTop: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 15,
    padding: 12,
    maxHeight: 280,
  },
  suggestionsTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#6c757d',
    marginBottom: 12,
    paddingHorizontal: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  suggestionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#E8F4F8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  suggestionIcon: {
    fontSize: 20,
  },
  suggestionText: {
    fontSize: 15,
    color: '#333',
    flex: 1,
    fontWeight: '500',
  },
  suggestionTextContainer: {
    flex: 1,
  },
  suggestionMainText: {
    fontSize: 15,
    color: '#212529',
    fontWeight: '600',
    marginBottom: 3,
  },
  suggestionSecondaryText: {
    fontSize: 13,
    color: '#6c757d',
  },
  suggestionArrow: {
    fontSize: 24,
    color: '#adb5bd',
    marginLeft: 10,
  },
  toggleSearchButton: {
    position: 'absolute',
    top: 60,
    right: 15,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4A90E2',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  toggleSearchIcon: {
    fontSize: 24,
    color: '#fff',
  },
  vozButton: {
    position: 'absolute',
    top: 130,
    right: 15,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#34C759',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  vozButtonIcon: {
    fontSize: 24,
  },
  instruccionActual: {
    position: 'absolute',
    bottom: 30,
    left: 15,
    right: 15,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  instruccionTexto: {
    fontSize: 18,
    color: '#fff',
    fontWeight: '600',
    marginBottom: 8,
    lineHeight: 24,
  },
  instruccionDistancia: {
    fontSize: 24,
    color: '#4A90E2',
    fontWeight: 'bold',
  },


});